### ISSUE TITLE
accountsmanager service bails out

### ISSUE THREAD

**Issue by parmentelat** [parmentelat/rhubarbe#1]
Observed on faraday

Not too serious in that it happens in rough conditions, but likely to cause avalanches. 

```
root@faraday /var/log # journalctl --unit=accountsmanager -n 50
-- Logs begin at Thu 2017-03-09 18:02:51 CET, end at Fri 2017-03-10 16:16:29 CET. --
Mar 09 18:02:56 faraday systemd[1]: Started testbed accounts manager - manages unix accounts and their authorized_keys.
Mar 09 18:03:23 faraday bash[1697]: ignored exception in GetSlices : [Errno -3] Temporary failure in name resolution
Mar 09 18:03:33 faraday bash[1697]: ignored exception in GetPersons : [Errno -3] Temporary failure in name resolution
Mar 09 18:05:40 faraday bash[1697]: ignored exception in GetKeys : [Errno 110] Connection timed out
Mar 09 18:05:40 faraday bash[1697]: Traceback (most recent call last):
Mar 09 18:05:40 faraday bash[1697]:   File "/usr/local/bin/rhubarbe-accounts", line 48, in main
Mar 09 18:05:40 faraday bash[1697]:     exit(entry_point(*args))
Mar 09 18:05:40 faraday bash[1697]:   File "/usr/local/lib/python3.5/dist-packages/rhubarbe/main.py", line 682, in accounts
Mar 09 18:05:40 faraday bash[1697]:     return accounts.main(args.cycle)
Mar 09 18:05:40 faraday bash[1697]:   File "/usr/local/lib/python3.5/dist-packages/rhubarbe/accounts.py", line 295, in main
Mar 09 18:05:40 faraday bash[1697]:     self.run_forever(cycle)
Mar 09 18:05:40 faraday bash[1697]:   File "/usr/local/lib/python3.5/dist-packages/rhubarbe/accounts.py", line 288, in run_forever
Mar 09 18:05:40 faraday bash[1697]:     time.sleep(period - duration)
Mar 09 18:05:40 faraday bash[1697]: ValueError: sleep length must be non-negative
Mar 09 18:05:40 faraday bash[1697]: /usr/local/bin/rhubarbe-accounts accounts : Something went badly wrong : sleep length must be non-ne
Mar 09 18:05:40 faraday systemd[1]: accountsmanager.service: Main process exited, code=exited, status=1/FAILURE
Mar 09 18:05:40 faraday systemd[1]: accountsmanager.service: Unit entered failed state.
Mar 09 18:05:40 faraday systemd[1]: accountsmanager.service: Failed with result 'exit-code'.
Mar 10 16:14:59 faraday systemd[1]: Stopped testbed accounts manager - manages unix accounts and their authorized_keys.
Mar 10 16:14:59 faraday systemd[1]: Started testbed accounts manager - manages unix accounts and their authorized_keys.
```

**Comment by parmentelat** [comment]
most likely this one is now obsolete
